global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    environment: "prod"
    cluster: "main"

rule_files:
  - /etc/prometheus/alert_rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  # Сам Prometheus
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Центральный сервер: системные метрики
  - job_name: "node_exporter"
    static_configs:
      - targets:
          - "192.168.0.4:9100"
        labels:
          nodename: "main"
      - targets:
          - "192.168.0.5:9100"
        labels:
          nodename: "analytics"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  # Контейнеры: cadvisor
  - job_name: "cadvisor"
    static_configs:
      - targets: ["192.168.0.4:8080"]
        labels:
          nodename: "main"
      - targets: ["192.168.0.5:8080"]
        labels:
          nodename: "analytics"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  # Python API
  - job_name: "demo_api"
    metrics_path: /metrics
    static_configs:
      - targets:
          - "192.168.0.4:8000"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance